---
name: 'Dokploy Deployment Suite'
description: 'Automate Dokploy deployments with health checks, rollback, zero-downtime, and comprehensive lifecycle management'
author: 'SSanjeevi'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  # ===== Core Configuration (Required) =====
  dokploy-url:
    description: 'The URL of your Dokploy instance (e.g., https://dokploy.example.com)'
    required: true

  api-key:
    description: 'API key for authenticating with Dokploy'
    required: true

  application-id:
    description: 'Dokploy application ID to deploy'
    required: true

  docker-image:
    description: 'Docker image to deploy (e.g., ghcr.io/user/app:v1.0.0)'
    required: true

  # ===== Deployment Control =====
  wait-for-completion:
    description: 'Wait for deployment to complete (true/false)'
    required: false
    default: 'true'

  timeout:
    description: 'Deployment timeout in seconds'
    required: false
    default: '300'

  # ===== Health Check Configuration =====
  enable-health-check:
    description: 'Enable health check after deployment (true/false)'
    required: false
    default: 'true'

  health-check-url:
    description: 'Health check endpoint URL (e.g., https://app.com/health)'
    required: false
    default: ''

  health-check-retries:
    description: 'Number of health check retries'
    required: false
    default: '10'

  health-check-interval:
    description: 'Interval between health check retries in seconds'
    required: false
    default: '6'

  expected-status-code:
    description: 'Expected HTTP status code for health check'
    required: false
    default: '200'

  # ===== Container Cleanup =====
  cleanup-old-containers:
    description: 'Cleanup old containers after successful deployment (true/false)'
    required: false
    default: 'false'

  container-prefix:
    description: 'Container name prefix for cleanup filtering'
    required: false
    default: ''

  keep-container-count:
    description: 'Number of old containers to keep'
    required: false
    default: '1'

  # ===== Rollback Configuration =====
  rollback-on-failure:
    description: 'Automatically rollback on deployment failure (true/false)'
    required: false
    default: 'true'

outputs:
  deployment-id:
    description: 'The deployment ID from Dokploy'
    value: ${{ steps.deploy.outputs.deployment-id }}

  deployment-status:
    description: 'The deployment status (success/failed/timeout)'
    value: ${{ steps.deploy.outputs.deployment-status }}

  health-status:
    description: 'Health check status (healthy/unhealthy/skipped)'
    value: ${{ steps.health-check.outputs.health-status }}

  containers-cleaned:
    description: 'Number of old containers cleaned up'
    value: ${{ steps.cleanup.outputs.removed-count }}

runs:
  using: 'node20'
  main: 'dist/index.js'
