---
name: 'Dokploy Deployment Suite'
description: 'Automate Dokploy deployments with health checks, rollback, zero-downtime, and comprehensive lifecycle management'
author: 'SSanjeevi'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  # ===== Core Configuration (Required) =====
  dokploy-url:
    description: 'The URL of your Dokploy instance (e.g., https://dokploy.example.com)'
    required: true

  api-key:
    description: 'API key for authenticating with Dokploy'
    required: true

  application-id:
    description: 'Dokploy application ID to deploy (optional if using project/environment/app names)'
    required: false
    default: ''

  docker-image:
    description: 'Docker image to deploy (e.g., ghcr.io/user/app:v1.0.0). Required for application deployments, optional for compose deployments.'
    required: false
    default: ''

  # ===== Project & Environment Management =====
  project-id:
    description: 'Dokploy project ID (optional if using project-name)'
    required: false
    default: ''

  project-name:
    description: 'Dokploy project name (will be created if not exists)'
    required: false
    default: ''

  project-description:
    description: 'Description for the project (used when creating new project)'
    required: false
    default: 'Automated deployment project'

  environment-id:
    description: 'Dokploy environment ID (optional if using environment-name)'
    required: false
    default: ''

  environment-name:
    description: 'Dokploy environment name (will be created if not exists)'
    required: false
    default: 'production'

  application-name:
    description: 'Dokploy application name (will be created/updated)'
    required: false
    default: ''

  server-name:
    description: 'Server name for deployment (e.g., Hostinger-Server1)'
    required: false
    default: ''

  auto-create-resources:
    description: 'Automatically create project/environment/application if they do not exist'
    required: false
    default: 'true'

  # ===== Deployment Control =====
  wait-for-completion:
    description: 'Wait for deployment to complete (true/false)'
    required: false
    default: 'true'

  timeout:
    description: 'Deployment timeout in seconds'
    required: false
    default: '20'

  # ===== Health Check Configuration =====
  enable-health-check:
    description: 'Enable health check after deployment (true/false)'
    required: false
    default: 'true'

  health-check-path:
    description: 'Health check endpoint path (e.g., /health or /)'
    required: false
    default: ''

  health-check-retries:
    description: 'Number of health check retries'
    required: false
    default: '10'

  health-check-interval:
    description: 'Interval between health check retries in seconds'
    required: false
    default: '6'

  fail-on-health-check-error:
    description: 'Fail the deployment if health check fails (true/false). Set to false to allow manual verification later.'
    required: false
    default: 'true'

  expected-status-code:
    description: 'Expected HTTP status code for health check'
    required: false
    default: '200'

  # ===== Container Cleanup =====
  cleanup-old-containers:
    description: 'Cleanup old containers after successful deployment (true/false)'
    required: false
    default: 'false'

  container-prefix:
    description: 'Container name prefix for cleanup filtering'
    required: false
    default: ''

  keep-container-count:
    description: 'Number of old containers to keep'
    required: false
    default: '1'

  # ===== Rollback Configuration =====
  rollback-on-failure:
    description: 'Automatically rollback on deployment failure (true/false)'
    required: false
    default: 'true'

  # ===== Resource Limits =====
  memory-limit:
    description: 'Maximum memory limit for container in MB (e.g., 512 for 512MB)'
    required: false
    default: ''

  memory-reservation:
    description: 'Soft memory reservation in MB (e.g., 256 for 256MB)'
    required: false
    default: ''

  cpu-limit:
    description: 'Maximum CPU limit (e.g., 1.0 for 1 CPU, 0.5 for half CPU)'
    required: false
    default: ''

  cpu-reservation:
    description: 'CPU reservation/guaranteed allocation (e.g., 0.25 for quarter CPU)'
    required: false
    default: ''

  restart-policy:
    description: 'Container restart policy: always, unless-stopped, on-failure, no'
    required: false
    default: 'unless-stopped'

  container-name:
    description: 'Custom container name. Supports templates: {app} (application name), {version} (image tag/version), {env} (environment name). Example: "{app}-{version}" becomes "myapp-v1.0.0"'
    required: false
    default: ''

  # ===== Docker Advanced Configuration =====
  volumes:
    description: 'Container volume mounts (one per line). Format: /host/path:/container/path or /host/path:/container/path:ro. Example: /var/run/docker.sock:/var/run/docker.sock'
    required: false
    default: ''

  group-add:
    description: 'Additional groups to add the container user to (comma-separated). Example: "988" for Docker group or "docker,sudo"'
    required: false
    default: ''

  # ===== Docker Compose & Template Deployments =====
  deployment-type:
    description: 'Deployment type: application (default) or compose. Use "compose" to deploy from docker-compose.yml or Dokploy template.'
    required: false
    default: 'application'

  compose-file:
    description: 'Path to docker-compose.yml file (relative to repository root). Used when deployment-type is "compose".'
    required: false
    default: ''

  compose-raw:
    description: 'Raw docker-compose.yml content as string. Alternative to compose-file. Used when deployment-type is "compose".'
    required: false
    default: ''

  compose-name:
    description: 'Name for the compose deployment. Required when deployment-type is "compose".'
    required: false
    default: ''

  dokploy-template-base64:
    description: 'Base64-encoded Dokploy template (from templates marketplace). Alternative to compose-file. Used when deployment-type is "compose".'
    required: false
    default: ''

  # ===== Scaling Configuration =====
  replicas:
    description: 'Number of container replicas to run (Docker Swarm)'
    required: false
    default: '1'

  # ===== Docker Registry Configuration =====
  registry-url:
    description: 'Docker registry URL (e.g., ghcr.io)'
    required: false
    default: 'ghcr.io'

  registry-username:
    description: 'Docker registry username'
    required: false
    default: ''

  registry-password:
    description: 'Docker registry password/token'
    required: false
    default: ''

  # ===== Environment Variables =====
  env:
    description: 'Environment variables as KEY=VALUE pairs, one per line'
    required: false
    default: ''

  env-file:
    description: 'Path to .env file with environment variables'
    required: false
    default: ''

  env-from-json:
    description: 'Environment variables in JSON format: {"KEY1":"value1","KEY2":"value2"}'
    required: false
    default: ''

  # ===== Domain Configuration =====
  domain-host:
    description: 'Domain host for the application (e.g., app.example.com)'
    required: false
    default: ''

  domain-path:
    description: 'Domain path prefix (e.g., /api)'
    required: false
    default: '/'

  application-port:
    description: 'Container port that the application listens on (not the domain port which is always 80/443)'
    required: false
    default: '80'

  domain-https:
    description: 'Enable HTTPS for domain (true/false)'
    required: false
    default: 'true'

  # ===== Advanced Options =====
  deployment-strategy:
    description: 'Deployment strategy: rolling, recreate'
    required: false
    default: 'rolling'

  debug-mode:
    description: 'Enable debug logging (true/false)'
    required: false
    default: 'false'

outputs:
  deployment-id:
    description: 'The deployment ID from Dokploy'
    value: ${{ steps.deploy.outputs.deployment-id }}

  deployment-status:
    description: 'The deployment status (success/failed/timeout)'
    value: ${{ steps.deploy.outputs.deployment-status }}

  health-status:
    description: 'Health check status (healthy/unhealthy/skipped)'
    value: ${{ steps.health-check.outputs.health-status }}

  containers-cleaned:
    description: 'Number of old containers cleaned up'
    value: ${{ steps.cleanup.outputs.removed-count }}

  project-id:
    description: 'The project ID (created or existing)'
    value: ${{ steps.deploy.outputs.project-id }}

  environment-id:
    description: 'The environment ID (created or existing)'
    value: ${{ steps.deploy.outputs.environment-id }}

  application-id:
    description: 'The application ID (created or updated)'
    value: ${{ steps.deploy.outputs.application-id }}

runs:
  using: 'node20'
  main: 'dist/index.js'
