---
name: 'Cleanup Old Containers'
description: 'Remove old containers with optional prefix filtering'
author: 'Dokploy Actions'

branding:
  icon: 'trash-2'
  color: 'red'

inputs:
  dokploy-url:
    description: 'Dokploy instance URL'
    required: true
  api-key:
    description: 'Dokploy API key'
    required: true
  application-id:
    description: 'Application ID'
    required: true
  container-prefix:
    description: 'Container name prefix to filter (optional)'
    required: false
    default: ''
  keep-count:
    description: 'Number of recent containers to keep'
    required: false
    default: '1'
  dry-run:
    description: 'Dry run mode (list containers without removing)'
    required: false
    default: 'false'

outputs:
  removed-count:
    description: 'Number of containers removed'
    value: ${{ steps.cleanup.outputs.removed-count }}
  kept-count:
    description: 'Number of containers kept'
    value: ${{ steps.cleanup.outputs.kept-count }}

runs:
  using: 'composite'
  steps:
    - name: List containers
      id: list
      shell: bash
      run: |
        echo "ðŸ“‹ Listing containers..."

        response=$(curl -s -X GET \
          "${{ inputs.dokploy-url }}/api/container.all?applicationId=${{ inputs.application-id }}" \
          -H "x-api-key: ${{ inputs.api-key }}")

        echo "$response" | jq -r '.containers[] | "\(.id) \(.name) \(.created)"' > /tmp/containers.txt || true

        if [ -s /tmp/containers.txt ]; then
          echo "Found containers:"
          cat /tmp/containers.txt
        else
          echo "No containers found"
        fi

    - name: Filter and cleanup
      id: cleanup
      shell: bash
      run: |
        echo "ðŸ§¹ Cleaning up old containers..."

        prefix="${{ inputs.container-prefix }}"
        keep_count=${{ inputs.keep-count }}
        dry_run="${{ inputs.dry-run }}"

        # Filter by prefix if provided
        if [ -n "$prefix" ]; then
          echo "Filtering containers with prefix: $prefix"
          grep "$prefix" /tmp/containers.txt > /tmp/filtered.txt || touch /tmp/filtered.txt
        else
          cp /tmp/containers.txt /tmp/filtered.txt
        fi

        # Sort by creation time (newest first) and skip the ones to keep
        total_count=$(wc -l < /tmp/filtered.txt)
        echo "Total containers: $total_count"
        echo "Keeping: $keep_count"

        if [ $total_count -le $keep_count ]; then
          echo "âœ… No containers to remove"
          echo "removed-count=0" >> $GITHUB_OUTPUT
          echo "kept-count=$total_count" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Get containers to remove (skip first N)
        tail -n +$((keep_count + 1)) /tmp/filtered.txt > /tmp/to_remove.txt

        removed=0
        while IFS= read -r line; do
          container_id=$(echo "$line" | awk '{print $1}')
          container_name=$(echo "$line" | awk '{print $2}')

          if [ "$dry_run" = "true" ]; then
            echo "ðŸ” [DRY RUN] Would remove: $container_name ($container_id)"
          else
            echo "ðŸ—‘ï¸ Removing: $container_name ($container_id)"

            curl -s -X POST \
              "${{ inputs.dokploy-url }}/api/container.remove" \
              -H "x-api-key: ${{ inputs.api-key }}" \
              -H "Content-Type: application/json" \
              -d "{\"containerId\": \"$container_id\"}" > /dev/null

            removed=$((removed + 1))
          fi
        done < /tmp/to_remove.txt

        kept=$keep_count

        echo "removed-count=$removed" >> $GITHUB_OUTPUT
        echo "kept-count=$kept" >> $GITHUB_OUTPUT

        if [ "$dry_run" = "true" ]; then
          echo "âœ… Dry run completed"
        else
          echo "âœ… Cleanup completed: removed $removed, kept $kept"
        fi

    - name: Cleanup summary
      if: always()
      shell: bash
      run: |
        echo "## ðŸ§¹ Container Cleanup Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Application ID**: ${{ inputs.application-id }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Container Prefix**: ${{ inputs.container-prefix || 'None' }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Removed**: ${{ steps.cleanup.outputs.removed-count }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Kept**: ${{ steps.cleanup.outputs.kept-count }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Dry Run**: ${{ inputs.dry-run }}" >> $GITHUB_STEP_SUMMARY
